services:
  vllm:
    container_name: vllm
    image: docker.io/vllm/vllm-openai:nightly
    restart: unless-stopped
    devices:
      - nvidia.com/gpu=all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      PYTORCH_ALLOC_CONF: expandable_segments:True
    volumes:
      - /ssd/internet/huggingface.co:/huggingface.co:ro
      - /home/nixos/vllm-cache:/root/.cache/vllm
    shm_size: 16g
    ports:
      - "8000:8000"
    command: >
      /huggingface.co/Qwen/Qwen3.6-27B-FP8
      --served-model-name Qwen3.6-27B-FP8
      --host 0.0.0.0
      --port 8000
      --max-model-len 262144
      --max-num-seqs 512
      --gpu-memory-utilization 0.95
      --kv-cache-dtype fp8
      --optimization-level 3
      --performance-mode interactivity
      --reasoning-parser qwen3
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --speculative-config '{"method":"qwen3_next_mtp","num_speculative_tokens":2}'

  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:16
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /home/nixos/forgejo-data:/data

  hermes:
    container_name: hermes
    image: docker.io/nousresearch/hermes-agent
    restart: unless-stopped
    volumes:
      - /home/nixos/tigor-ai/.hermes:/opt/data
      - /home/nixos/.ssh:/opt/hermes/.ssh:ro
    ports:
      - "9119:9119"
    environment:
      HERMES_DASHBOARD: "1"
    command: ["gateway", "run"]

  # caddy:
  #   container_name: caddy
  #   image: docker.io/library/caddy:2
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - /home/nixos/tigor-ai.public-for-http:/srv/data
  #     - /home/nixos/pages-data/caddy-data:/data
  #     - /home/nixos/pages-data/caddy-config:/config
  #   restart: unless-stopped
